
exports.getById = function(iid){
   return HY_ITEMS[iid.toString()];
};

var HY_ITEMS = {
	//food:食品,drug:药品,tool:工具,prop:道具,spe:特殊道具,inv :不可见物品
	// 工作台
	"4000":{
		ID : "4000",
		NAME : "石块",
		DESC : "厚重的石块，是建造和制作的重要材料",
		TYPE : "prop",
		WEIGHT : "3",
		VALUE : "1",
		
	},
	"4001":{
		ID : "4001",
		NAME : "阔叶",
		DESC : "宽大而结实的树叶，无论是用来遮挡还是包裹都非常合适",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "1",
	},
	"4002":{
		ID : "4002",
		NAME : "淡水",
		DESC : "干净的淡水，可直接使用",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "2",
	},
	"4003":{
		ID : "4003",
		NAME : "藤条",
		DESC : "结实的藤条，用途非常多",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "2",
	},
	"4004":{
		ID : "4004",
		NAME : "木材",
		DESC : "质地良好的木材，可以承担比较大的负重，用途很广泛",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "1",
	},
	"4005":{
		ID : "4005",
		NAME : "石片",
		DESC : "很薄的石片，稍加打磨就可以变得锋利",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "5",
	},
	"4006":{
		ID : "4006",
		NAME : "硬木",										//弃用
		DESC : "异常坚硬的木头，虽然加工起来麻烦，但是很耐用",
		TYPE : "prop",
		WEIGHT : "2",
		VALUE : "2",
	},
	"4007":{
		ID : "4007",
		NAME : "铁矿",
		DESC : "天然的铁矿石，可通过熔炉提炼出铁",
		TYPE : "prop",
		WEIGHT : "3",
		VALUE : "5",
	},
	"4008":{
		ID : "4008",
		NAME : "干草",										//弃用
		DESC : "蓬松的干草，用来制作床铺和衣物都是不错的选择",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "1",
	},
	"4009":{
		ID : "4009",
		NAME : "猪牙",										//弃用
		DESC : "野猪的牙齿，很锋利",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "3",
	},
	"4010":{
		ID : "4010",										//猪皮筏任务物品
		NAME : "完整的猪皮",
		DESC : "完整的猪皮，充气后浮力可观",
		TYPE : "inv",
		WEIGHT : "0",
		VALUE : "0",
	},
	"4011":{
		ID : "4011",
		NAME : "兽皮",
		DESC : "野兽的毛皮，质感和保暖性俱佳",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "5",
	},
	"4012":{
		ID : "4012",
		NAME : "兽筋",
		DESC : "野兽筋，拥有非常高的韧性",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "5",
	},
	"4013":{
		ID : "4013",
		NAME : "药草",
		DESC : "常见草药，用于脾胃气虚，倦怠乏力",
		TYPE : "drug",
		WEIGHT : "1",
		VALUE : "2",
		ATTRS : {"7005" : 15},
	},
	"4014":{
		ID : "4014",
		NAME : "藿香",										//弃用
		DESC : "常见草药，可用来杀菌，同时也有清热解毒功效",
		TYPE : "drug",
		WEIGHT : "1",
		VALUE : "2",
	},
	// "4015":{
	// 	ID : "4015",
	// 	NAME : "兽血",										//弃用
	// 	DESC : "猛兽的鲜血，可以用来入药",
	// 	TYPE : "prop",
	// 	WEIGHT : "1",
	// 	VALUE : "1",
	// },
	"4016":{
		ID : "4016",
		NAME : "绷带",
		DESC : "采用草药和藤条制作出来的粗糙绷带，具有一定的治疗外伤功效",
		TYPE : "drug",
		WEIGHT : "1",
		VALUE : "4",
		ATTRS : {"7004" : 30},
	},
	"4017":{
		ID : "4017",
		NAME : "汤药",
		DESC : "利用草药加工而成的药剂，可用于治疗感染",
		TYPE : "drug",
		WEIGHT : "1",
		VALUE : "4",
		ATTRS : {"7005" : 45},
	},
	"4018":{
		ID : "4018",
		NAME : "急救丸",
		DESC : "珍贵的急救丸，加工难度较高，但效果良好，对治疗内伤和失眠有奇效",
		TYPE : "drug",
		WEIGHT : "1",
		VALUE : "20",
		ATTRS : {"7005" : 100,"7001" : -100},
	},
	"4019":{
		ID : "4019",
		NAME : "药酒",
		DESC : "由酒精和药草混合而成的药酒，用于治疗外伤",
		TYPE : "drug",
		WEIGHT : "1",
		VALUE : "8",
		ATTRS : {"7004" : 60},
	},
	"4020":{
		ID : "4020",
		NAME : "生肉",
		DESC : "新鲜的生肉，一般作为食材加工后食用",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "1",
		ATTRS : {"7006" : 20,"7005" : -5},
	},
	"4021":{
		ID : "4021",
		NAME : "椰子",
		DESC : "富含糖分和微量元素，在荒岛上称得上是生命之果",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "1",
		ATTRS : {"7006" : 15},
	},
	"4022":{
		ID : "4022",
		NAME : "薄荷",
		DESC : "以薄荷代茶，清心明目",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "1",
	},
	"4023":{
		ID : "4023",
		NAME : "野菜",										//弃用
		DESC : "烹饪的时候加一点野菜才能做出美味的食物",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "1",
	},
	"4024":{
		ID : "4024",
		NAME : "薄荷茶",
		DESC : "以薄荷泡出的茶，可清心明目",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "2",
		ATTRS : {"7001" : -50},
	},
	"4025":{
		ID : "4025",
		NAME : "烤肉",
		DESC : "经过烤制加工的肉，口感不错且不易感染",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "3",
		ATTRS : {"7006" : 40},
	},
	"4025_1":{
		ID : "4025_1",
		NAME : "美味烤肉",
		DESC : "经过烤制加工的肉，口感不错且不易感染，比一般的更加美味",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "3",
		ATTRS : {"7006" : 46},
	},	
	"4026":{
		ID : "4026",
		NAME : "肉汤",
		DESC : "用鲜肉加少许佐料精心烹制而出的肉汤，十分美味",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "5",
		ATTRS : {"7006" : 85},
	},
	"4026_1":{
		ID : "4026_1",
		NAME : "美味肉汤",
		DESC : "用鲜肉加少许佐料精心烹制而出的肉汤，十分美味，比一般的更加美味",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "5",
		ATTRS : {"7006" : 97},
	},	
	"4027":{
		ID : "4027",
		NAME : "宠物口粮",
		DESC : "专门用于给宠物喂食的口粮，深得宠物喜爱",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "4",
	},
	"4028":{
		ID : "4028",
		NAME : "树脂",
		DESC : "树木上取下来的树脂，可当做燃料",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "2",
	},
	"4029":{
		ID : "4029",
		NAME : "珍珠",
		DESC : "珍贵的珍珠，闪闪发光，价值不菲",
		TYPE : "spe",
		WEIGHT : "1",
		VALUE : "5",
	},
	"4030":{
		ID : "4030",
		NAME : "木炭",
		DESC : "木头燃烧之后得到的木炭，用途较多",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "2",
	},
	"4031":{
		ID : "4031",
		NAME : "粘土",
		DESC : "粘土，是制作物品时的重要材料",
		TYPE : "prop",
		WEIGHT : "2",
		VALUE : "2",
	},
	"4032":{
		ID : "4032",
		NAME : "软金",
		DESC : "具有很高延展性，可用来制作高级物品",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "4",
	},
	"4033":{
		ID : "4033",
		NAME : "羊毛",
		DESC : "羊身上的毛，拥有很强的保暖性",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "4",
	},
	"4034":{
		ID : "4034",
		NAME : "硫磺",
		DESC : "硫磺，制作火药的重要材料之一",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "3",
	},
	"4035":{
		ID : "4035",
		NAME : "硝石",
		DESC : "硝石，制作火药的重要材料之一",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "3",
	},
	"4036":{
		ID : "4036",
		NAME : "竹子",
		DESC : "野生的竹子，可加工成多种工具",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "2",
	},
	"4037":{
		ID : "4037",
		NAME : "酒精",
		DESC : "从土豆酒中提炼出来的酒精，浓度很高，有多种用途",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "4",
	},
	"4038":{
		ID : "4038",
		NAME : "蜂蜜",
		DESC : "冒着被蜂蛰的危险掏出来的蜂蜜，可以食用恢复饥饿度并且提神",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "2",
		ATTRS : {
			"7006" : 5,
			"7001" : -10,
		},
	},
	"4039":{
		ID : "4039",
		NAME : "人参",
		DESC : "野生的人参，有着很强的药用性",
		TYPE : "drug",
		WEIGHT : "1",
		VALUE : "4",
		ATTRS : {"7005" : 40},
	},
	"4040":{
		ID : "4040",
		NAME : "烤土豆",
		DESC : "土豆通过简单的烤制制成，熟食不易造成感染",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "3",
		ATTRS : {"7006" : 35},
	},
	"4040_1":{
		ID : "4040_1",
		NAME : "美味烤土豆",
		DESC : "土豆通过简单的烤制制成，熟食不易造成感染，比一般的更加美味",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "3",
		ATTRS : {"7006" : 40},
	},	
	"4041":{
		ID : "4041",
		NAME : "土豆泥",
		DESC : "土豆烤熟之后捣碎而成的土豆泥，更易消化",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "3",
		ATTRS : {"7006" : 70},
	},
	"4041_1":{
		ID : "4041_1",
		NAME : "美味土豆泥",
		DESC : "土豆烤熟之后捣碎而成的土豆泥，更易消化，比一般的更加美味",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "3",
		ATTRS : {"7006" : 80},
	},	
	"4042":{
		ID : "4042",
		NAME : "土豆酒",
		DESC : "用土豆发酵酿造的酒，味道不错",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "8",
		ATTRS : {"7001" : -30},
	},
	"4043":{
		ID : "4043",
		NAME : "秘制炖肉",
		DESC : "多种食材和调料制成的炖肉，在味道和分量上都有大幅度提升",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "6",
		ATTRS : {"7006" : 100 , "7001" : -25},
	},
	"4043_1":{
		ID : "4043_1",
		NAME : "美味秘制炖肉",
		DESC : "多种食材和调料制成的炖肉，在味道和分量上都有大幅度提升，比一般的更加美味",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "6",
		ATTRS : {"7006" : 115 , "7001" : -29},
	},	
	"4044":{
		ID : "4044",
		NAME : "土豆",
		DESC : "土豆，经过加工味道较好，直接生食可能会造成感染",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "2",
		ATTRS : {"7006" : 10 , "7005" : -3},
	},
	"4045":{				//弃用
		ID : "4045",
		NAME : "油料",
		DESC : "奇怪的油料，不知道什么用途",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "2",
	},
	"4046":{				
		ID : "4046",
		NAME : "急救包",
		DESC : "原地复活，状态全满",
		TYPE : "prop",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4047":{											//热气球线和帆船线关键道具
		ID : "4047",
		NAME : "特殊的帆布",
		DESC : "厚实完整的帆布，似乎有着特殊的用处",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4048":{											//海盗船关键道具
		ID : "4048",
		NAME : "海盗船",
		DESC : "海盗手上缴获的船只，可以用来逃离荒野",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4049":{											//帆船线关键道具
		ID : "4049",
		NAME : "铁锭",
		DESC : "铁矿熔铸出来的铁锭，含铁量大大提高。",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},	

	"4050":{											//热气球线关键道具
		ID : "4050",
		NAME : "油料",
		DESC : "可以充分燃烧的燃料，可提供大量热能。",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4051":{											//热气球线关键道具
		ID : "4051",
		NAME : "结实的木材",
		DESC : "相比普通木材更结实，可以用来建造坚固大船",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4052":{											//火山爆发事件道具
		ID : "4052",
		NAME : "火山爆发",
		DESC : "猛烈的火山爆发会吞噬、摧毁大片土地，把大批生命、物资烧为灰烬。",
		TYPE : "inv",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4061":{											//神秘路线道具
		ID : "4061",
		NAME : "赤色圆球",
		DESC : "神秘的赤色圆球",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4062":{											//神秘路线道具
		ID : "4062",
		NAME : "橙色圆球",
		DESC : "神秘的橙色圆球",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4063":{											//神秘路线道具
		ID : "4063",
		NAME : "黄色圆球",
		DESC : "神秘的黄色圆球",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4064":{											//神秘路线道具
		ID : "4064",
		NAME : "绿色圆球",
		DESC : "神秘的绿色圆球",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4065":{											//神秘路线道具
		ID : "4065",
		NAME : "青色圆球",
		DESC : "神秘的青色圆球",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4066":{											//神秘路线道具
		ID : "4066",
		NAME : "蓝色圆球",
		DESC : "神秘的蓝色圆球",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4067":{											//神秘路线道具
		ID : "4067",
		NAME : "紫色圆球",
		DESC : "神秘的紫色圆球",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},	

	"4068":{
		ID : "4068",
		NAME : "仙豆",
		DESC : "神奇的豆子，只要吃下一粒就可以使人伤口愈合、精神抖擞。来源是个谜，据说由真挚的友谊浇灌而成。",
		TYPE : "food",
		WEIGHT : "0",
		VALUE : "2",
		ATTRS : {"7000" : 1000 , "7001" : -1000, "7003" : 1000, "7004" : 1000, "7005" : 1000, "7006" : 1000},
	},

	"4069":{
		ID : "4069",										//猪皮筏任务物品
		NAME : "粗壮的竹子",
		DESC : "野生的竹子，可加工成多种工具",
		TYPE : "inv",
		WEIGHT : "0",
		VALUE : "0",
	},

	"4070":{
		ID : "4070",
		NAME : "荒野烤肉",
		DESC : "罗兰开发的菜系，加入了特殊的调料，除了能填饱肚子，还有提神醒脑的作用",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "3",
		ATTRS : {"7006" : 60, "7001" : -10},
	},

	"4070_1":{
		ID : "4070_1",
		NAME : "美味荒野烤肉",
		DESC : "罗兰开发的菜系，加入了特殊的调料，除了能填饱肚子，还有提神醒脑的作用，比一般的更加美味",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "3",
		ATTRS : {"7006" : 75, "7001" : -15},
	},

	"4071":{
		ID : "4071",
		NAME : "羽毛",
		DESC : "很整齐的羽毛，用来做什么比较好呢？",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "0",
	},
	"4072":{
		ID : "4072",
		NAME : "毒液",
		DESC : "从大自然提取的毒素，或许能派上大用途",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "1",
	},
	"4073":{
		ID : "4073",
		NAME : "背鳍",
		DESC : "旗鱼的背鳍，留着可能有用",
		TYPE : "spe",
		WEIGHT : "1",
		VALUE : "0",
	},
	"4074":{
		ID : "4074",
		NAME : "鱼油",
		DESC : "从鱼类身上提取的鱼油，是很好的材料",
		TYPE : "prop",
		WEIGHT : "1",
		VALUE : "1",
	},
	"4075":{
		ID : "4075",
		NAME : "石板",
		DESC : "从遗迹中获取的石板，需要找到能看懂的人",
		TYPE : "spe",
		WEIGHT : "5",
		VALUE : "1",
	},
	"4076":{
		ID : "4076",
		NAME : "荒野秘宝",
		DESC : "可以进入崖洞、遗迹深处的秘宝",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "1",
	},
	"4077":{
		ID : "4077",
		NAME : "绳索",
		DESC : "可以进入崖洞",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "1",
	},	
	"4078":{
		ID : "4078",
		NAME : "祭品",
		DESC : "可以进入遗迹深处",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "1",
	},	
	"4079":{
		ID : "4079",
		NAME : "子弹制造图纸",
		DESC : "上面记载了如何手工制造子弹，但是好像必须要有冶金台才能制作",
		TYPE : "spe",
		WEIGHT : "0",
		VALUE : "0",
	},
	"4080":{
		ID : "4080",
		NAME : "真子弹制造图纸",
		DESC : "作为cond判定的物品",
		TYPE : "inv",
		WEIGHT : "0",
		VALUE : "0",
	},





	"7006":{											
		ID : "7006",
		NAME : "喂食",
		DESC : "用生肉喂食宠物，可恢复其饱食度80点，饱食度不足则无法出战",
		TYPE : "inv",
		WEIGHT : "0",
		VALUE : "0",
	},
	"7010":{											
		ID : "7010",
		NAME : "生火",
		DESC : "生火使室温提高，持续6小时",
		TYPE : "inv",
		WEIGHT : "0",
		VALUE : "0",
	},
	"7028":{									
		ID : "7028",
		NAME : "驯养",
		DESC : "用宠物口粮驯养宠物，可恢复其忠诚度80点，忠诚度越高攻击越高",
		TYPE : "inv",
		WEIGHT : "0",
		VALUE : "0",
	},

	"7003":{									
		ID : "7003",
		NAME : "治疗",
		DESC : "用药草治疗宠物，可恢复其生命值80点，生命值不足则无法出战",
		TYPE : "inv",
		WEIGHT : "0",
		VALUE : "0",
	},





	//4100开始为工具类    1远程 2近战 3衣服 4照明 5炸药包
	//装备无论近战或者远程武器，实际攻击力都是空手攻击力+武器攻击力，空手攻击力15。
	//空手攻击距离为1，攻击速度为1
	//-1表示通用武器

	"0":{//拳头攻击15
		ID : "0",
		// NAME : "拳头",
		// DESC : "石制的斧头，虽然不是那么好用，但是砍树也还凑活",
		// TYPE : "tool",
		// DURATION : "50",
		// WEIGHT : "6",
		// VALUE : "3",
		// E_TYPE : "2",
		// OPEN_TIME : 30,
		// OPEN_DUR : 5,
		ATK_NDESC : ["握紧双拳，狠狠挥向", "大喝一声，用拳头砸向"],	//普通状态攻击描述
		ATK_TDESC : ["感到很疲惫，但为了活下去，奋力用双拳挥向"], //疲惫状态攻击描述
		// E_ATTRS : {
		// 	ATK : 15,
		// 	DIS : 1,
		// 	SPD : 1,
		// 	},
		AUDIO : "attack_fist",
	},

	
	
	
	"4100":{
		ID : "4100",
		NAME : "石斧",
		DESC : "石制的斧头，杀伤力一般，可用来砍伐",
		TYPE : "tool",
		DURATION : "120",
		WEIGHT : "5",
		VALUE : "3",
		E_TYPE : "2",
		OPEN_TIME : 30,
		OPEN_DUR : 5,
		ATK_NDESC : ["挥起石斧，砍向", "握紧斧柄，挥向"],	
		ATK_TDESC : ["强打起精神，挥起石斧，砍向", "强打起精神，握紧斧柄，挥向"],
		E_ATTRS : {
			ATK : 20,
			DIS : 1,
			SPD : 1,
		},
		AUDIO : "attack_blunt",
	},
	"4100_1":{
		ID : "4100_1",
		NAME : "耐久石斧",
		DESC : "石制的斧头，杀伤力一般，可用来砍伐，比一般的更加耐用",
		TYPE : "tool",
		DURATION : "156",
		WEIGHT : "5",
		VALUE : "3",
		E_TYPE : "2",
		OPEN_TIME : 30,
		OPEN_DUR : 5,
		ATK_NDESC : ["挥起石斧，砍向", "握紧斧柄，挥向"],	
		ATK_TDESC : ["强打起精神，挥起石斧，砍向", "强打起精神，握紧斧柄，挥向"],
		E_ATTRS : {
			ATK : 20,
			DIS : 1,
			SPD : 1,
		},
		AUDIO : "attack_blunt",
	},	
	"4101":{
		ID : "4101",
		NAME : "匕首",
		DESC : "通过打磨变得更加锋利，可以用来切割，也可以用来砍伐",
		TYPE : "tool",
		WEIGHT : "1",
		VALUE : "4",
		DURATION : "50",		
		E_TYPE : "2",
		ATK_NDESC : ["挥起匕首，砍向", "握紧匕首，挥向"],	
		ATK_TDESC : ["虽然状态不佳，依然挥起匕首，砍向", "虽然状态不佳，依然握紧匕首，挥向"],
		E_ATTRS : {
			ATK : 20,
			DIS : 1,
			SPD : 1,
			},
		AUDIO : "attack_sharp",
		},
	"4102":{			//弃用
		ID : "4102",
		NAME : "泰罗克的羽毛",
		DESC : "泰罗克身上羽毛制做成长矛，威力巨大",
		TYPE : "tool",
		WEIGHT : "6",
		VALUE : "4",
		DURATION : "99999",
		E_TYPE : "2",
		ATK_NDESC : ["挥起泰罗克的羽毛，砍向", "握紧泰罗克的羽毛，挥向"],	
		ATK_TDESC : ["虽然状态很不佳，依然挥起泰罗克的羽毛，砍向", "虽然状态很不佳，依然握紧泰罗克的羽毛，挥向"],
		E_ATTRS : {
			ATK : 500,
			DIS : 10,
			SPD : 1,
			},
		AUDIO : "attack_sharp",
		},
	"4103":{
		ID : "4103",
		NAME : "武士刀",
		DESC : "按照标准化的锻造流程制造而成，杀伤力巨大",
		TYPE : "tool",
		WEIGHT : "6",
		VALUE : "10",
		DURATION : "150",
		E_TYPE : "2",
		ATK_NDESC : ["挥起武士刀，砍向", "握紧刀柄，挥向"],	
		ATK_TDESC : ["即使如此疲惫之下，依然挥起武士刀，砍向", "即使如此疲惫之下，依然握紧刀柄，挥向"],
		E_ATTRS : {
			ATK : 45,
			DIS : 1,
			SPD : 1,
			},
		AUDIO : "attack_sharp",
		},
	"4104":{
		ID : "4104",
		NAME : "硬竹弩",
		DESC : "构造十分复杂精巧的弩机，伤害不俗",
		TYPE : "tool",
		WEIGHT : "5",
		VALUE : "10",
		DURATION : "60",
		E_TYPE : "1",
		ATK_NDESC : ["拉开竹弩，搭上羽箭，射向"],	
		ATK_TDESC : ["勉强打起精神，扣动扳机射向"],
		E_ATTRS : {
			ATK : 65,
			DIS : 10,
			SPD : 2,
			HIT : 90,
			},
		AUDIO : "attack_arrow",
		},
	"4104_1":{
		ID : "4104_1",
		NAME : "耐久硬竹弩",
		DESC : "构造十分复杂精巧的弩机，伤害不俗，比一般的更加耐用",
		TYPE : "tool",
		WEIGHT : "5",
		VALUE : "10",
		DURATION : "90",
		E_TYPE : "1",
		ATK_NDESC : ["拉开竹弩，搭上羽箭，射向"],	
		ATK_TDESC : ["勉强打起精神，扣动扳机射向"],
		E_ATTRS : {
			ATK : 65,
			DIS : 10,
			SPD : 2,
			HIT : 90,
			},
		AUDIO : "attack_arrow",
		},		
	"4105":{
		ID : "4105",
		NAME : "短弓",
		DESC : "粗制的短弓，杀伤力普通",
		TYPE : "tool",
		WEIGHT : "4",
		VALUE : "4",
		DURATION : "50",
		E_TYPE : "1",
		ATK_NDESC : ["拉开短弓，搭上羽箭，射向"],	
		ATK_TDESC : ["勉强打起精神，拉开短弓，搭上羽箭，射向"],
		E_ATTRS : {
			ATK : 25,
			DIS : 6,
			SPD : 1,
			HIT : 90,
			},
		AUDIO : "attack_arrow",
		},
	"4105_1":{
		ID : "4105_1",
		NAME : "耐久短弓",
		DESC : "粗制的短弓，杀伤力普通，比一般的更加耐用",
		TYPE : "tool",
		WEIGHT : "4",
		VALUE : "4",
		DURATION : "65",
		E_TYPE : "1",
		ATK_NDESC : ["拉开短弓，搭上羽箭，射向"],	
		ATK_TDESC : ["勉强打起精神，拉开短弓，搭上羽箭，射向"],
		E_ATTRS : {
			ATK : 25,
			DIS : 6,
			SPD : 1,
			HIT : 90,
			},
		AUDIO : "attack_arrow",
		},		
	"4106":{
		ID : "4106",
		NAME : "硬竹弓",
		DESC : "射程和伤害方面都比短弓稍微强一些的武器",
		TYPE : "tool",
		WEIGHT : "5",
		VALUE : "5",
		DURATION : "60",
		E_TYPE : "1",
		ATK_NDESC : ["拉开长弓，搭上羽箭，射向"],	
		ATK_TDESC : ["勉强打起精神，拉开长弓，搭上羽箭，射向"],
		E_ATTRS : {
			ATK : 45,
			DIS : 7,
			SPD : 1,
			HIT : 95,
			},
		AUDIO : "attack_arrow",
		},
	"4106_1":{
		ID : "4106_1",
		NAME : "耐久硬竹弓",
		DESC : "射程和伤害方面都比短弓稍微强一些的武器，比一般的更加耐用",
		TYPE : "tool",
		WEIGHT : "5",
		VALUE : "5",
		DURATION : "78",
		E_TYPE : "1",
		ATK_NDESC : ["拉开长弓，搭上羽箭，射向"],	
		ATK_TDESC : ["勉强打起精神，拉开长弓，搭上羽箭，射向"],
		E_ATTRS : {
			ATK : 45,
			DIS : 7,
			SPD : 1,
			HIT : 95,
			},
		AUDIO : "attack_arrow",
		},		
	"4107":{
		ID : "4107",
		NAME : "箭矢",
		DESC : "好弓配好箭，无箭不成弓。需携带后配合弓、弩使用。",
		TYPE : "tool",
		WEIGHT : "0",
		VALUE : "0.1",
		DURATION : "1",
	},
	"4108":{
		ID : "4108",												//弃用
		NAME : "诱捕网",								
		DESC : "用来诱捕动物的网子，偶尔会失败",
		TYPE : "tool",
		WEIGHT : "3",
		VALUE : "3",
		DURATION : "100",
	},
	"4109":{
		ID : "4109",
		NAME : "皮甲",
		DESC : "兽皮制成的衣服，有一定的防御和御寒能力",
		TYPE : "tool",
		WEIGHT : "2",
		VALUE : "8",
		DURATION : "200",
		E_TYPE : "3",
		E_ATTRS : {
			DEF : 5,
			},
	},
	"4110":{
		ID : "4110",
		NAME : "鞋",		//弃用
		DESC : "不用赤脚走路速度要快多了",
		TYPE : "tool",
		WEIGHT : "0",
		VALUE : "0",
		DURATION : "1000",
	},
	"4111":{
		ID : "4111",
		NAME : "包",		
		DESC : "结实的背包，制造后提高20点负重上限，仅可制造一次",
		TYPE : "inv",
		WEIGHT : "0",
		VALUE : "0",
		DURATION : "1000",
	},
	"4112":{
		ID : "4112",
		NAME : "双刃斧",		
		DESC : "在初代石斧的基础上进行改造，加上了杀伤力和造型",
		TYPE : "tool",
		WEIGHT : "6",
		VALUE : "4",
		DURATION : "130",
		E_TYPE : "2",
		ATK_NDESC : ["挥起双刃斧，砍向", "握紧斧柄，挥向"],	
		ATK_TDESC : ["勉强打起精神，挥起双刃斧，砍向", "勉强打起精神，握紧斧柄，挥向"],
		OPEN_TIME : 20 ,
		OPEN_DUR : 5 ,		
		E_ATTRS : {
			ATK : 30,
			DIS : 1,
			SPD : 1,
			},
		AUDIO : "attack_sharp",
	},
	"4112_1":{
		ID : "4112_1",
		NAME : "耐久双刃斧",		
		DESC : "在初代石斧的基础上进行改造，加上了杀伤力和造型，比一般的更加耐用",
		TYPE : "tool",
		WEIGHT : "6",
		VALUE : "4",
		DURATION : "169",
		E_TYPE : "2",
		ATK_NDESC : ["挥起双刃斧，砍向", "握紧斧柄，挥向"],	
		ATK_TDESC : ["勉强打起精神，挥起双刃斧，砍向", "勉强打起精神，握紧斧柄，挥向"],
		OPEN_TIME : 20 ,
		OPEN_DUR : 5 ,		
		E_ATTRS : {
			ATK : 30,
			DIS : 1,
			SPD : 1,
			},
		AUDIO : "attack_sharp",
	},	
	"4113":{
		ID : "4113",
		NAME : "竹枪",		
		DESC : "用竹子和石片拼起来的竹枪，攻击距离比斧头远",
		TYPE : "tool",
		WEIGHT : "3",
		VALUE : "3",
		DURATION : "90",
		E_TYPE : "2",
		ATK_NDESC : ["挥起竹枪，刺向", "握紧竹枪，挥向"],	
		ATK_TDESC : ["勉强打起精神，挥起竹枪，刺向", "勉强打起精神，握紧竹枪，挥向"],
		E_ATTRS : {
			ATK : 18,
			DIS : 3,
			SPD : 1,
			},
		AUDIO : "attack_sharp",
	},
	"4113_1":{
		ID : "4113_1",
		NAME : "耐久竹枪",		
		DESC : "用竹子和石片拼起来的竹枪，攻击距离比斧头远，比一般的更加耐用",
		TYPE : "tool",
		WEIGHT : "3",
		VALUE : "3",
		DURATION : "115",
		E_TYPE : "2",
		ATK_NDESC : ["挥起竹枪，刺向", "握紧竹枪，挥向"],	
		ATK_TDESC : ["勉强打起精神，挥起竹枪，刺向", "勉强打起精神，握紧竹枪，挥向"],
		E_ATTRS : {
			ATK : 18,
			DIS : 3,
			SPD : 1,
			},
		AUDIO : "attack_sharp",
	},	
	"4114":{
		ID : "4114",
		NAME : "火把",	
		DESC : "火把可以提高夜里探险的安全性，并在使用远程武器的时候不受黑暗影响",
		TYPE : "tool",
		WEIGHT : "4",
		VALUE : "3",
		DURATION : "100",
		E_TYPE : "4",
	},
	"4115":{
		ID : "4115",
		NAME : "重连弩",		
		DESC : "用金属打造的弩，比竹制的有更强的杀伤力，并且更不易损坏",
		TYPE : "tool",
		WEIGHT : "6",
		VALUE : "7",
		DURATION : "100",
		E_TYPE : "1",
		ATK_NDESC : ["拉开连弩，搭上箭矢，射向"],	
		ATK_TDESC : ["勉强打起精神，扣动扳机射向"],
		E_ATTRS : {
			ATK : 85,
			DIS : 10,
			SPD : 2,
			HIT : 95,
			RECYCLE : 0,
			},
		AUDIO : "attack_arrow",
	},
	"4116":{
		ID : "4116",
		NAME : "藤甲",		
		DESC : "竹子和兽皮制作的护甲，防御力进一步提升，里面的羊毛还起到保暖的作用",
		TYPE : "tool",
		WEIGHT : "3",
		VALUE : "8",
		DURATION : "1000",
		E_TYPE : "3",
		E_ATTRS : {
			DEF : 10,
			DODGE : 0,
			},
	},
	"4117":{
		ID : "4117",
		NAME : "竹筒炸药",		
		DESC : "利用竹子制造的原始炸药，杀伤力巨大，但有可能哑火",
		TYPE : "tool",
		WEIGHT : "3",
		VALUE : "4",
		DURATION : "1",
		E_TYPE : "5",
		E_ATTRS : {
			ATK : 120,
			DIS : 5,
			RANGE : 2,
			HIT : 100,
			FAIL : 10,
		},
		AUDIO : "attack_bomb",
	},
	"4118":{
		ID : "4118",
		NAME : "精致炸药",	
		DESC : "利用金属材料加工的炸药，稳定性和杀伤力都大幅度提升",
		TYPE : "tool",
		WEIGHT : "4",
		VALUE : "8",
		DURATION : "1",
		E_TYPE : "5",
		E_ATTRS : {
			ATK : 170,
			DIS : 5,
			RANGE : 2,
			HIT : 100,
			FAIL : 0,
		},
		AUDIO : "attack_bigbomb",
	},
	"4119":{
		ID : "4119",
		NAME : "老贝的草裙",
		DESC : "老贝亲手制作的草裙，利用了迷彩的理念，有时可以降低野兽的命中率。",
		TYPE : "tool",
		WEIGHT : "2",
		VALUE : "10",
		DURATION : "200",
		E_TYPE : "3",
		E_ATTRS : {
			DEF : 5,
			DODGE : 15,
			// DODGE : 100,//测试
			},
	},
	"4120":{
		ID : "4120",
		NAME : "朱莉的长弓",		
		DESC : "朱莉曾经用过的弓，精巧的制作能让弓箭射出后不易损坏，有概率在战后回收箭矢。",
		TYPE : "tool",
		WEIGHT : "4",
		VALUE : "10",
		DURATION : "300",
		E_TYPE : "1",
		ATK_NDESC : ["拉开长弓，搭上箭矢，射向"],	
		ATK_TDESC : ["勉强打起精神，拉开长弓，搭上羽箭，射向"],
		E_ATTRS : {
			ATK : 30,
			DIS : 6,
			SPD : 1,
			HIT : 100,
			RECYCLE : 20,
			// RECYCLE : 100,//测试
			},
		AUDIO : "attack_arrow",
	},
	"4120_1":{
		ID : "4120_1",
		NAME : "耐久朱莉的长弓",		
		DESC : "朱莉曾经用过的弓，精巧的制作能让弓箭射出后不易损坏，有概率在战后回收箭矢，比一般的更加耐用",
		TYPE : "tool",
		WEIGHT : "4",
		VALUE : "10",
		DURATION : "390",
		E_TYPE : "1",
		ATK_NDESC : ["拉开长弓，搭上箭矢，射向"],	
		ATK_TDESC : ["勉强打起精神，拉开长弓，搭上羽箭，射向"],
		E_ATTRS : {
			ATK : 30,
			DIS : 6,
			SPD : 1,
			HIT : 100,
			RECYCLE : 20,
			// RECYCLE : 100,//测试
			},
		AUDIO : "attack_arrow",
	},		
	"4121":{
		ID : "4121",
		NAME : "闪避护符",
		DESC : "不知道哪里穿越而来的闪避护符，100%闪避攻击",
		TYPE : "tool",
		WEIGHT : "2",
		VALUE : "10",
		DURATION : "200",
		E_TYPE : "3",
		E_ATTRS : {
			DEF : 4,
			// DODGE : 15,
			DODGE : 100,//测试
			},
	},
	"4122":{
		ID : "4122",
		NAME : "索利达尔，群星之怒",		
		DESC : "利用魔法力量凝聚箭矢",
		TYPE : "tool",
		WEIGHT : "4",
		VALUE : "10",
		DURATION : "99999",
		E_TYPE : "1",
		ATK_NDESC : ["拉开索利达尔，群星之怒，搭上箭矢，射向"],	
		ATK_TDESC : ["勉强打起精神，拉开索利达尔，群星之怒，搭上羽箭，射向"],
		E_ATTRS : {
			ATK : 400,
			DIS : 10,
			SPD : 1,
			HIT : 100,
			// RECYCLE : 20,
			RECYCLE : 100,//测试
			},
		AUDIO : "attack_arrow",
	},
	"4123":{
		ID : "4123",
		NAME : "毒羽箭",
		DESC : "从野蛮人那里学习来的特殊制法的箭矢，平衡性好且杀伤力大",
		TYPE : "tool",
		WEIGHT : "0",
		VALUE : "0.1",
		DURATION : "1",
	},

	"4124":{
		ID : "4124",
		NAME : "小哥的手电",	
		DESC : "随小哥一起穿越的手电，能在黑暗中照亮前行的道路，轻便持久",
		TYPE : "tool",
		WEIGHT : "2",
		VALUE : "0",
		DURATION : "350",
		E_TYPE : "4",
	},

	"4125":{
		ID : "4125",
		NAME : "袖珍手枪",
		DESC : "虽然粗糙，但是杀伤力和命中率还是比弓弩强很多，要不是破损严重，估计更好用",
		TYPE : "tool",
		WEIGHT : "4",
		VALUE : "4",
		DURATION : "150",
		E_TYPE : "1",
		ISGUN : "1",
		ATK_NDESC : ["装填弹药，扣动扳机，射向"],	
		ATK_TDESC : ["勉强打起精神，装填弹药，扣动扳机，射向"],
		E_ATTRS : {
			ATK : 105,
			DIS : 8,
			SPD : 1,
			HIT : 110,
			},
		AUDIO : "attack_arrow",
		},

	"4126":{
		ID : "4126",
		NAME : "弹药",
		DESC : "专用于袖珍手枪的弹药",
		TYPE : "tool",
		WEIGHT : "0",
		VALUE : "0.1",
		DURATION : "1",		
	},




	"5001":{
		ID : "5001",
		NAME : "鲳鱼",
		DESC : "体短而高，略呈菱形。\n吃起来很有满足感。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 25,"7000" : 10},
	},
    "5002":{
		ID : "5002",
		NAME : "鲷鱼",
		DESC : "长相漂亮，味道鲜美，雌雄同体。\n轻度缓解气血虚弱。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 22,"7005" : 6},
	},
	"5003":{
		ID : "5003",
		NAME : "海参",
		DESC : "色暗，多肉刺，触手轮形，有毒性。\n略微提神，能提取出毒液。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 15,"7001" : -6},
		ITEMS : {"4072" : 1},
	},
	"5004":{
		ID : "5004",
		NAME : "海鲂",
		DESC : "体扁平，口大。\n对恢复伤口有一定帮助。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 22,"7004" : 8},
	},
	"5005":{
		ID : "5005",
		NAME : "海鲈鱼",
		DESC : "体型粗而长，蛋白质丰富，肉质鲜美。\n肉质坚实。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 25},
	},
	"5006":{
		ID : "5006",
		NAME : "海豚鱼",
		DESC : "不知是海豚还是鱼。\n有杀菌的功效。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 20,"7005" : 10},
	},
	"5007":{
		ID : "5007",
		NAME : "河豚",
		DESC : "有一定毒性，遇到危险时会吸气膨胀。\n毒性较难祛除干净，但能让人精神一振。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "2",
		ISFISH : true,
		ATTRS : {"7006" : 20,"7001" : -20,"7005" : -6},
		ITEMS : {"4072" : 2},
	},
	"5008":{
		ID : "5008",
		NAME : "河虾",
		DESC : "普通的河虾，是很好的鱼饵。\n虾青素是很好的抗氧化剂。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 10,"7000" : 4},
	},
	"5009":{
		ID : "5009",
		NAME : "岩鱼",
		DESC : "形似鲈，口大，眼大，头上及颊部均有棘刺。\n虽然很好吃，但是要注意棘刺。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 25,"7004" : -8},
	},
	"5010":{
		ID : "5010",
		NAME : "黑鱼",
		DESC : "生性凶猛，繁殖力强，胃口奇大。\n生肌补血，短期内促进伤口愈合。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 25},
		BUFFS : ["7000"],
	},
	"5011":{
		ID : "5011",
		NAME : "红鲑鱼",
		DESC : "红色肉质，含油量高。\n略微缓解失眠和内伤，短期内能提高精神。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 28,"7001" : -6,"7005" : 6},
		ITEMS : {"4074" : 1},
		BUFFS : ["7001"],
	},
	"5012":{
		ID : "5012",
		NAME : "蝴蝶鱼",
		DESC : "外形优美，品质嫩滑、清香宜人。\n短期提高灵敏度。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 20,"7001" : -4},
		BUFFS : ["7002"],
	},
	"5013":{
		ID : "5013",
		NAME : "虎纹岩鱼",
		DESC : "长着虎纹的岩鱼，有不错的杀伤力。\n短期内提高攻击。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 30,"7000" : 6},
		BUFFS : ["7003"],
	},
	"5014":{
		ID : "5014",
		NAME : "剑鱼",
		DESC : "非常巨大，富含脂肪，鱼身似剑。\n略微恢复内外伤，鱼腹中也许有惊喜。",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "2",
		ISFISH : true,
		ATTRS : {"7006" : 35,"7004" : 6,"7005" : 6},
		ITEMS : {"4101" : 1},
	},
	"5015":{
		ID : "5015",
		NAME : "蓝鳍金枪鱼",
		DESC : "非常珍贵的一种鱼，有着漂亮的蓝色鱼鳍。\n对全身都有一定恢复效果，短期内提高攻防。",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "2",
		ISFISH : true,
		ATTRS : {"7006" : 40,"7000" : 6,"7001" : -6,"7004" : 6,"7005" : 6},
		BUFFS : ["7004"],
	},
	"5016":{
		ID : "5016",
		NAME : "老虎斑",
		DESC : "鱼皮厚，头腩丰满，多肉爽脆。\n对伤口愈合有着不错的效果。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 35,"7004" : 12},
    },
	"5017":{
		ID : "5017",
		NAME : "龙虾",
		DESC : "胸部较粗大，外壳坚硬，脂肪含量低。\n居然还有龙虾？",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 10,"7000" : 4},
    },
	"5018":{
		ID : "5018",
		NAME : "罗非鱼",
		DESC : "外形类似鲫鱼，鳍条多棘，形似鳜鱼。\n能促进伤口愈合，但似乎不易消化。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 20,"7004" : 12,"7005" : -6},
    },
	"5019":{
		ID : "5019",
		NAME : "泥鳅",
		DESC : "常见的泥鳅，浑身沾满自己的粘液。\n作为鱼饵似乎不错。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 10},
    },
	"5020":{
		ID : "5020",
		NAME : "鲶鱼",
		DESC : "体长形，头部平扁，尾部侧扁。\n补中益阳，调理内伤。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 20,"7005" : 6},
    },
	"5021":{
		ID : "5021",
		NAME : "螃蟹",
		DESC : "螃蟹虽小，却是五脏俱全。\n短期内略微提升防御。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 20},
		BUFFS : ["7005"],
    },
	"5022":{
		ID : "5022",
		NAME : "旗鱼",
		DESC : "外形略扁，呈流线型，肌肉发达，第一背鳍长而高。\n略微缓解失眠，背鳍很有特点。",
		TYPE : "food",
		WEIGHT : "2",
		VALUE : "2",
		ISFISH : true,
		ATTRS : {"7006" : 30,"7001" : -6},
		ITEMS : {"4073" : 1},
    },
	"5023":{
		ID : "5023",
		NAME : "鲭鱼",
		DESC : "体粗壮微扁，呈纺锤形。\n肉质坚实。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 30},
    },
	"5024":{
		ID : "5024",
		NAME : "秋刀鱼",
		DESC : "体延长而纤细，侧扁，有不错的味道。\n短期内略微提升攻击。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 10},
		BUFFS : ["7006"],
    },
	"5025":{
		ID : "5025",
		NAME : "三文鱼",
		DESC : "体侧扁，背部隆起，齿尖锐，鳞片细小。\n虽然促进外伤愈合，但生食可能造成感染。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 20,"7004" : 12,"7005" : -4},
    },
	"5026":{
		ID : "5026",
		NAME : "石斑鱼",
		DESC : "体长椭圆形稍侧扁，具条纹和斑点。\n给大家带来了很多欢乐。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 25,"7000" : 10},
    },
	"5027":{
		ID : "5027",
		NAME : "锯齿鲤",
		DESC : "体呈卵圆形，侧扁，牙齿锋利。\n小心被牙齿伤到，一定时间内大幅度提高攻击。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "2",
		ISFISH : true,
		ATTRS : {"7006" : 32,"7004" : -8},
		BUFFS : ["7007"],
    },
	"5028":{
		ID : "5028",
		NAME : "条石鲷",
		DESC : "体延长而呈长卵圆形，侧扁而高，矿物质含量丰富。\n短期内持续恢复内伤。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 30},
		BUFFS : ["7010"],
    },
	"5029":{
		ID : "5029",
		NAME : "鳕鱼",
		DESC : "体延长，稍侧扁。\n短期内有效提高抗寒能力。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "2",
		ISFISH : true,
		ATTRS : {"7006" : 32},
		BUFFS : ["7009"],
		ITEMS : {"4074" : 1},
    },
	"5030":{
		ID : "5030",
		NAME : "章鱼",
		DESC : "体卵形或卵圆形，肌肉强健，味道鲜美。\n短期内提高命中率。",
		TYPE : "food",
		WEIGHT : "1",
		VALUE : "1",
		ISFISH : true,
		ATTRS : {"7006" : 20},
		BUFFS : ["7008"],
    },
};