exports.getTips = function(bid){
	// return dy.utils.clone(HY_TIPS[bid.toString()]);
	let arr = HY_TIPS[bid];
	return arr[dy.utils.random(0, arr.length - 1)];
};


var HY_TIPS = {
	"1":[//新玩家
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"我的身边发生巨大的灾难",
			"这使我流落到了无人的荒野",
			"我所要做的",
			"就是活下去",
		],
		[
			"我的名字是<strong><color=#E53333>{name}</color></strong>",
			"这是我的故事",
			"也是你的故事",
			"倘若我没有从这里逃出",
			"请你继承我的意志",
		],
		[
			"我写下属于我的故事",
			"也同样属于你的故事",
			"这是无人的荒野",
			"请你带我逃离这里",
			"<strong><color=#E53333>{name}</color></strong>",
			"拜托你了",
		],
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"我现在缺少食物",
			"缺少干净的水",
			"缺少一张舒适的床",
			"我甚至不知道自己在哪",
			"一定要活着出去",
		],
	],
	"2":[//活有逃出
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"身为荒野求生的大师",
			"我已经成功逃离荒野<strong><color=#E53333>{escape}</color></strong>次",
			"这次已经生存了<strong><color=#E53333>{aliveTime}</color></strong>天",
			"我还有一个心愿",
			"收集齐神秘圆球",
		],
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"我在这片荒野生存了<strong><color=#E53333>{aliveTime}</color></strong>天",
			"这不是我第一次流落荒野了",
			"我觉得冥冥之中",
			"这片荒野",
			"有什么东西在召唤着我",
		],
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"我曾从荒野逃离<strong><color=#E53333>{escape}</color></strong>次",
			"然而这片荒野似乎不寻常",
			"我再次回到这里",
			"生存了<strong><color=#E53333>{aliveTime}</color></strong>天",
			"探寻未曾发现的秘密",
		],
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"虽然我已经逃离了<strong><color=#E53333>{escape}</color></strong>次",
			"但相比现代社会的尔虞我诈",
			"我更喜爱亲近自然",
			"只是这已经是第<strong><color=#E53333>{aliveTime}</color></strong>天了",
			"恐怕得先逃出去",
			"暂时还不想死在这里",
		],
	],
	"3":[//活无逃出
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"我已经在这片荒野生存了<strong><color=#E53333>{aliveTime}</color></strong>天",
			"我还能逃出这里",
			"回到属于我的地方么",
			
		],
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"这是我在荒野的第<strong><color=#E53333>{aliveTime}</color></strong>天",
			"我都快忘了怎么说话",
			"这样下去坚持不了多久",
			"我一定要尽快逃离这里",
		],
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"说出来你可能不信",
			"<strong><color=#E53333>{aliveTime}</color></strong>天，这是我在这里生存的天数",
			"我不确定我能不能看见明天的日出",
			"人类在自然面前真是渺小啊",
		],
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"我竟然已经在这生存了<strong><color=#E53333>{aliveTime}</color></strong>天",
			"哎，我真是天才",
			"可是",
			"我不想死啊",
			"不想死啊",
		],
	],
	"4":[//死
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"死在荒野的第<strong><color=#E53333>{aliveTime}</color></strong>天",
			"或许对食物的安排更精细些",
			"或许对药物的储备更多一些",
			"我就不会死了吧",
			"好不甘心啊",
		],
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"在这过去的<strong><color=#E53333>{aliveTime}</color></strong>天里",
			"我无时无刻不想逃离这片荒野",
			"我想念家里温暖的床铺",
			"想念妈妈做的菜",
			"可我再也吃不到了",
		],
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"<strong><color=#E53333>{aliveTime}</color></strong>天，我的死期",
			"请将我葬在绸缎中",
			"让我躺在铺满玫瑰的床上",
			"在黎明时分将我沉入河中",
			"来生逃出这诡异的荒野",
		],
		[
			"我叫<strong><color=#E53333>{name}</color></strong>",
			"听说人死得时候会闪回一生",
			"现在到我死时",
			"才知道这是无稽之谈",
			"<strong><color=#E53333>{aliveTime}</color></strong>天",
			"麻烦下次活的久一些",
		],
	],
};